export const REMOVE_POST = 'REMOVE_POST';
export const SET_POST = 'SET_POST';

export const FETCH_POSTS_START = 'FETCH_POSTS_START';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_SUCCESS';
